// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeTyv2MLss2VWSBttQhHL9SGBHt2RUN1c',
    appId: '1:670602954347:web:387a42dcc10b888ba6d32e',
    messagingSenderId: '670602954347',
    projectId: 'proyecto-moviles-umas',
    authDomain: 'proyecto-moviles-umas.firebaseapp.com',
    storageBucket: 'proyecto-moviles-umas.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsp8ecBTgwCTVg9izUHJScELeT8S7L_7I',
    appId: '1:670602954347:android:2ee4086b3d3dfb4ca6d32e',
    messagingSenderId: '670602954347',
    projectId: 'proyecto-moviles-umas',
    storageBucket: 'proyecto-moviles-umas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHDjBHPVma4gLWWHz3HasC8YXE7jO-2m4',
    appId: '1:670602954347:ios:fc6125b08653daeca6d32e',
    messagingSenderId: '670602954347',
    projectId: 'proyecto-moviles-umas',
    storageBucket: 'proyecto-moviles-umas.firebasestorage.app',
    iosClientId: '670602954347-2fblblhtbk8fm4krf6b3i5voftmqmril.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectoMoviles',
  );
}
